### ISSUE TITLE
View Helper for Exposing Data to JS

### ISSUE THREAD

**Issue by joshrowley** [carrot/roots-yaml#1]
Adding a view helper so that

``` jade
= yaml('some_string')
```

would add a script tag that would set `var some_string = <your yaml data>`

**Comment by FranzSkuffka** [comment]
The implementation of the helper was giving me some trouble when trying to use the roots-yaml for building a multilang-website. I actually needed the data in my templates and thus added a json option to this plugin.

https://github.com/FranzSkuffka/roots-yaml/commit/9937634bba96e1a0494c4438de44ae0d37b2f7c8

**Comment by jenius** [comment]
@FranzSkuffka this addition is redundant. You can get the data as json directly from `data` or whatever else you set the `source` option to in your settings.
